Extend `SigningCallback` form to allow returning an object
stellar/js-stellar-base pull request #783
Opened 2024-11-13 19:17 UTC by Shaptic

Closes https://github.com/stellar/js-stellar-base/issues/780 per discussion in https://github.com/stellar/js-stellar-base/pull/772#discussion_r1764307846.

2024-11-14 02:03 UTC, overcat requested changes

2024-11-14 02:03 UTC, overcat commented on types/index.d.ts
> +  { signature: BufferLike, publicKey: BufferLike }
```suggestion
  { signature: BufferLike, publicKey: string }
```

2024-11-14 17:17 UTC, Shaptic commented on CHANGELOG.md
> +  { signature: BufferLike, publicKey: BufferLike }
Ah you're right. I had it as a buffer previously then forgot to update it in all places.

2024-11-15 02:37 UTC, overcat approved these changes
LGTM!

2024-11-25 13:53 UTC, kalepail commented
I don't feel like I have much to add here. What I'm working on doesn't involve signing with G-addresses much anymore so I wouldn't be using this. If I do sign with a G-address the entire auth flow is custom as per whatever the __check_auth `signature` arg determines. Which this definitely isn't supporting, but that isn't to say such a method isn't useful, just that I can't really speak to it.

2025-03-26 17:42 UTC, merged